### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by crobertsbmw** [xpg/GizwitsBLE#6]
It would be super helpful if you could update the README to include how to get started. Basic usage and some documentation would help a lot rather than letting people try reverse engineer the sample app.

**Comment by crobertsbmw** [comment]
Also adding install instructions would be helpful. I cloned the project but can't seem to figure out how to get it to run with android studio.

**Comment by ax003d** [comment]
This is basically an eclipse project. BleLibrary is the library project you can reuse in your own project. And BluetoothLeGatt is the example project use the BleLibrary.
Will update readme soon.
